#!/bin/csh -f

setenv JLAB_ROOT /opt/jlab_software
setenv USER root
source $JLAB_ROOT/devel/ce/jlab.csh

echo "#########################################"
csh $JLAB_ROOT/devel/install/go_clhep
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_xercesc
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_geant4
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_sconsscript
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_evio
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_mysql
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_ccdb
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_mlibrary
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_gemc
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_fields
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_root
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_banks
echo "#########################################"
csh $JLAB_ROOT/devel/install/go_jana
echo "done"
